/*
================================================================================
  FILE: 01_governance/03_tag_enforcement.sql
  PURPOSE: Enforce cost attribution tags at object creation time using
           Snowflake Tag Policies. Prevents new warehouses and schemas from
           going live without a cost_center tag.
  REQUIRES: Enterprise Edition | ACCOUNTADMIN or FINOPS_ADMIN with APPLY TAG
  DOCUMENTATION: https://docs.snowflake.com/en/user-guide/tag-based-masking-policies
                 https://docs.snowflake.com/en/user-guide/object-tagging
================================================================================

  ⚠️ ENTERPRISE EDITION ONLY
  Tag-based policies (the enforcement mechanism) require Enterprise Edition.
  The tag definitions themselves work on Standard Edition, but enforcement
  without policies relies on auditing after the fact (see Section 4).

  WHY THIS MATTERS:
  Without enforcement, the "Untagged" bucket in your attribution reports grows
  back every time someone creates a new warehouse. This script closes that gap
  by requiring the cost_center tag before a warehouse can be activated.
*/


-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 1: Tag definitions
-- ─────────────────────────────────────────────────────────────────────────────
-- Tags must exist before they can be applied or referenced in policies.
-- Run these even on Standard Edition — they work everywhere.

-- Use a central schema for tag management so privileges are easy to control.
CREATE DATABASE IF NOT EXISTS GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE.TAGS;

USE SCHEMA GOVERNANCE.TAGS;

-- Cost center: which business unit or team owns this object.
-- ALLOWED_VALUES enforces a controlled vocabulary — free-text tags cause
-- inconsistencies in your attribution reports (e.g., 'Analytics' vs 'analytics').
CREATE TAG IF NOT EXISTS COST_CENTER
    ALLOWED_VALUES 'analytics', 'data_engineering', 'ml_platform', 'finance',
                   'shared_infra', 'platform'
    COMMENT = 'Business unit responsible for costs generated by this object.';

-- Team owner: email or alias for the team that owns this object.
-- Free text — allows email addresses or Slack channel names.
CREATE TAG IF NOT EXISTS TEAM_OWNER
    COMMENT = 'Team or individual responsible for this object. Use team email or alias.';

-- Environment: prevents dev workloads from appearing in prod cost reports.
CREATE TAG IF NOT EXISTS ENVIRONMENT
    ALLOWED_VALUES 'prod', 'staging', 'dev', 'sandbox', 'ci'
    COMMENT = 'Deployment environment for this object.';

-- Project: optional, for project-level chargebacks.
CREATE TAG IF NOT EXISTS PROJECT
    COMMENT = 'Project or initiative this object supports. Free text.';


-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 2: Grant tag usage to teams
-- ─────────────────────────────────────────────────────────────────────────────
-- Teams need READ access to see tag definitions.
-- FINOPS_ADMIN needs APPLY access to tag objects on behalf of teams.

GRANT USAGE ON DATABASE GOVERNANCE TO ROLE FINOPS_ADMIN;
GRANT USAGE ON SCHEMA GOVERNANCE.TAGS TO ROLE FINOPS_ADMIN;
GRANT READ  ON TAG GOVERNANCE.TAGS.COST_CENTER  TO ROLE FINOPS_ADMIN;
GRANT READ  ON TAG GOVERNANCE.TAGS.TEAM_OWNER   TO ROLE FINOPS_ADMIN;
GRANT READ  ON TAG GOVERNANCE.TAGS.ENVIRONMENT  TO ROLE FINOPS_ADMIN;
GRANT READ  ON TAG GOVERNANCE.TAGS.PROJECT      TO ROLE FINOPS_ADMIN;

-- Allow FINOPS_ADMIN to apply these tags to any object in the account:
GRANT APPLY ON TAG GOVERNANCE.TAGS.COST_CENTER TO ROLE FINOPS_ADMIN;
GRANT APPLY ON TAG GOVERNANCE.TAGS.TEAM_OWNER  TO ROLE FINOPS_ADMIN;
GRANT APPLY ON TAG GOVERNANCE.TAGS.ENVIRONMENT TO ROLE FINOPS_ADMIN;
GRANT APPLY ON TAG GOVERNANCE.TAGS.PROJECT     TO ROLE FINOPS_ADMIN;

-- For self-service tagging: allow teams to apply tags to their own objects.
-- Replace ANALYTICS_ROLE with the team's actual role name.
-- GRANT APPLY ON TAG GOVERNANCE.TAGS.COST_CENTER TO ROLE ANALYTICS_ROLE;


-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 3: Apply tags to existing objects
-- ─────────────────────────────────────────────────────────────────────────────
-- Run this for all existing warehouses and databases before enabling enforcement.
-- Enforcement (Section 4) will block new object creation without tags —
-- make sure everything existing is tagged first.

-- Warehouses
ALTER WAREHOUSE ANALYTICS_WH   SET TAG GOVERNANCE.TAGS.COST_CENTER = 'analytics',
                                        GOVERNANCE.TAGS.TEAM_OWNER  = 'analytics-team@company.com',
                                        GOVERNANCE.TAGS.ENVIRONMENT = 'prod';

ALTER WAREHOUSE DE_WH           SET TAG GOVERNANCE.TAGS.COST_CENTER = 'data_engineering',
                                        GOVERNANCE.TAGS.TEAM_OWNER  = 'de-team@company.com',
                                        GOVERNANCE.TAGS.ENVIRONMENT = 'prod';

ALTER WAREHOUSE ML_WH           SET TAG GOVERNANCE.TAGS.COST_CENTER = 'ml_platform',
                                        GOVERNANCE.TAGS.TEAM_OWNER  = 'ml-team@company.com',
                                        GOVERNANCE.TAGS.ENVIRONMENT = 'prod';

ALTER WAREHOUSE DEV_WH          SET TAG GOVERNANCE.TAGS.COST_CENTER = 'platform',
                                        GOVERNANCE.TAGS.TEAM_OWNER  = 'platform-team@company.com',
                                        GOVERNANCE.TAGS.ENVIRONMENT = 'dev';

-- Databases (tag propagates to schemas and tables within)
ALTER DATABASE ANALYTICS_DB     SET TAG GOVERNANCE.TAGS.COST_CENTER = 'analytics';
ALTER DATABASE ML_DB            SET TAG GOVERNANCE.TAGS.COST_CENTER = 'ml_platform';


-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 4: Audit untagged objects (works on Standard and Enterprise)
-- ─────────────────────────────────────────────────────────────────────────────
-- Run this regularly to catch objects created without tags.
-- This is the fallback enforcement mechanism if you are on Standard Edition.

-- Warehouses without COST_CENTER tag
SELECT
    t.DOMAIN,
    t.OBJECT_NAME,
    t.TAG_VALUE
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES t
WHERE t.TAG_NAME = 'COST_CENTER'
  AND t.DOMAIN   = 'WAREHOUSE';

-- Compare against all warehouses to find the untagged ones:
-- (Run SHOW WAREHOUSES first, then join)
SHOW WAREHOUSES;
SELECT
    w."name"    AS warehouse_name,
    w."size"    AS size,
    w."owner"   AS owner
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) w
WHERE w."name" NOT IN (
    SELECT OBJECT_NAME
    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
    WHERE TAG_NAME   = 'COST_CENTER'
      AND DOMAIN     = 'WAREHOUSE'
      AND TAG_VALUE IS NOT NULL
);

-- NOTE: TAG_REFERENCES has up to 3 hours of latency. A warehouse tagged in the
-- last 3 hours may still appear as untagged in this query.


-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 5: Tag policy enforcement (Enterprise Edition only)
-- ─────────────────────────────────────────────────────────────────────────────
-- A tag policy blocks object creation or activation when required tags are missing.
-- This is more restrictive than the audit above — it prevents the problem
-- rather than detecting it after the fact.
--
-- ⚠️ Test in a dev account before applying to production.
--    A misconfigured policy can block all warehouse creation for all users.

-- Create a policy that requires COST_CENTER before a warehouse can be used:
CREATE OR REPLACE TAG POLICY GOVERNANCE.TAGS.require_cost_center_on_warehouse
    FOR WAREHOUSE
    REQUIRED TAGS (GOVERNANCE.TAGS.COST_CENTER)
    COMMENT = 'All warehouses must have a COST_CENTER tag before they can be activated.';

-- Apply the policy to the account (affects all future warehouse creation):
-- ⚠️ Uncomment only after tagging all existing warehouses in Section 3.
-- ALTER ACCOUNT ADD TAG POLICY GOVERNANCE.TAGS.require_cost_center_on_warehouse;

-- To remove the policy if it causes issues:
-- ALTER ACCOUNT DROP TAG POLICY GOVERNANCE.TAGS.require_cost_center_on_warehouse;


-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 6: Verify tag values on existing objects
-- ─────────────────────────────────────────────────────────────────────────────

-- All warehouse tags currently applied:
SELECT
    OBJECT_NAME          AS warehouse_name,
    TAG_NAME,
    TAG_VALUE
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE DOMAIN     = 'WAREHOUSE'
  AND TAG_SCHEMA = 'TAGS'
ORDER BY OBJECT_NAME, TAG_NAME;

-- Check a specific object's tags:
SELECT SYSTEM$GET_TAG(
    'GOVERNANCE.TAGS.COST_CENTER',
    'ANALYTICS_WH',
    'WAREHOUSE'
) AS cost_center_value;


-- ─────────────────────────────────────────────────────────────────────────────
-- TROUBLESHOOTING
-- ─────────────────────────────────────────────────────────────────────────────
/*
  ISSUE: Tag not appearing in TAG_REFERENCES after applying it
  FIX:   TAG_REFERENCES has up to 3 hours of latency. Wait and re-query.
         For immediate verification, use SYSTEM$GET_TAG() instead — it reads
         current state without latency.

  ISSUE: ALLOWED_VALUES violation when applying a tag
  FIX:   The value you are trying to apply is not in the ALLOWED_VALUES list.
         Either use a listed value or add the new value to the tag definition:
           ALTER TAG GOVERNANCE.TAGS.COST_CENTER ADD ALLOWED_VALUES 'new_team';

  ISSUE: Tag policy blocking legitimate warehouse creation
  FIX:   Remove the policy temporarily:
           ALTER ACCOUNT DROP TAG POLICY GOVERNANCE.TAGS.require_cost_center_on_warehouse;
         Tag the warehouse, then re-apply the policy.

  ISSUE: Tag applied at database level not showing in TAG_REFERENCES for tables
  FIX:   Tag inheritance (parent object tags propagating to child objects) is
         reflected in SYSTEM$GET_TAG() but may not appear directly in TAG_REFERENCES
         for child objects. Use SYSTEM$GET_TAG on the specific object to check
         inherited values.
*/
